[package]
name = "dbust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tui = "0.19"
zbus = { version = "3.2", default-features = false, features = ["tokio", "xml"] }
crossterm = "0.25"
rand = "0.8"
tokio = { version = "1.21", features = ["full"] }