[package]
name = "dbust"
version = "0.1.0"
edition = "2021"
default-run = "dterm"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tui = "0.19"
tui-tree-widget = "0.12" # We can change to ratatui when tree-widget is in ratatui :)
zbus = { version = "3.14", default-features = false, features = ["tokio", "xml"] }
crossterm = "0.27"
tokio = { version = "1.32", features = ["full"] }
async-recursion = "1.0.4"
itertools = "0.11.0"
clap = { version = "4.4.1", features = ["derive"] }
